# Generated by Django 3.1.5 on 2021-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210623_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(upload_to='static/auctions/uploads'),
        ),
    ]
