# Generated by Django 3.1.5 on 2021-06-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210623_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(upload_to='auctions/static/auctions/uploads'),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentbidby', to=settings.AUTH_USER_MODEL)),
                ('listing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidon', to='auctions.listing')),
            ],
        ),
    ]
