# Generated by Django 3.1.5 on 2021-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210624_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
