# Generated by Django 3.1.5 on 2021-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210624_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='current_bid_by',
            new_name='bid_by',
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
