# Generated by Django 3.1.5 on 2021-06-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210624_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidby', to=settings.AUTH_USER_MODEL),
        ),
    ]
