# Generated by Django 3.1.5 on 2021-06-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_name',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_name',
            field=models.ManyToManyField(related_name='bidon', to='auctions.Listing'),
        ),
    ]
