# Generated by Django 3.1.5 on 2021-06-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210625_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_name',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidon', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
