# Generated by Django 3.1.5 on 2021-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210625_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=True),
        ),
    ]
